# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployWebsite

  displayName: 'Deploy website'

  jobs:

    - deployment: DeployWebsite

      displayName: 'Deploy website'

      environment: 

        name: Test-ENV

        resourceType: VirtualMachine

      strategy:

       runOnce:

           deploy:

            steps:

              - script:   sudo mkdir Ram